---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '6'
    k8s.eip.work/ingress: 'true'
    k8s.eip.work/service: NodePort
    k8s.eip.work/workload: db-phpmyadmin
  labels:
    k8s.eip.work/layer: db
    k8s.eip.work/name: db-phpmyadmin
  name: db-phpmyadmin
  namespace: dev
  resourceVersion: '3046112'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.eip.work/layer: db
      k8s.eip.work/name: db-phpmyadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.eip.work/layer: db
        k8s.eip.work/name: db-phpmyadmin
    spec:
      containers:
        -
          env:
            - name: PMA_HOST
              value: 10.96.156.230
            - name: PMA_PORT
              value: '3306'
          image: phpmyadmin/phpmyadmin
          imagePullPolicy: IfNotPresent
          name: phpmyadmin
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits: {}
            requests: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.eip.work/workload: db-phpmyadmin
  labels:
    k8s.eip.work/layer: db
    k8s.eip.work/name: db-phpmyadmin
  name: db-phpmyadmin
  namespace: dev
  resourceVersion: '3046073'
spec:
  clusterIP: 10.96.248.218
  ports:
    - name: 3a4yqt
      nodePort: 30730
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.eip.work/layer: db
    k8s.eip.work/name: db-phpmyadmin
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    k8s.eip.work/workload: db-phpmyadmin
  labels:
    k8s.eip.work/layer: db
    k8s.eip.work/name: db-phpmyadmin
  name: db-phpmyadmin
  namespace: dev
spec:
  rules:
    - host: myadmin.dev.hankutech.com
      http:
        paths:
          - backend:
              serviceName: db-phpmyadmin
              servicePort: 3a4yqt
            path: /


