---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
    k8s.eip.work/displayName: kuboard
    k8s.eip.work/ingress: 'true'
    k8s.eip.work/service: NodePort
    k8s.eip.work/workload: kuboard
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"k8s.eip.work/displayName":"kuboard","k8s.eip.work/ingress":"true","k8s.eip.work/service":"NodePort","k8s.eip.work/workload":"kuboard"},"labels":{"k8s.eip.work/layer":"monitor","k8s.eip.work/name":"kuboard"},"name":"kuboard","namespace":"kube-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s.eip.work/layer":"monitor","k8s.eip.work/name":"kuboard"}},"template":{"metadata":{"labels":{"k8s.eip.work/layer":"monitor","k8s.eip.work/name":"kuboard"}},"spec":{"containers":[{"image":"eipwork/kuboard:latest","imagePullPolicy":"Always","name":"kuboard"}],"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}]}}}}
  labels:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: kuboard
  name: kuboard
  namespace: kube-system
  resourceVersion: '2766273'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.eip.work/layer: monitor
      k8s.eip.work/name: kuboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.eip.work/layer: monitor
        k8s.eip.work/name: kuboard
    spec:
      containers:
        -
          image: 'eipwork/kuboard:latest'
          imagePullPolicy: Always
          name: kuboard
          resources:
            limits: {}
            requests: {}
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.eip.work/displayName: kuboard
    k8s.eip.work/workload: kuboard
    kubectl.kubernetes.io/last-applied-configuration: >-
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kuboard","namespace":"kube-system"},"spec":{"ports":[{"name":"http","nodePort":32567,"port":80,"targetPort":80}],"selector":{"k8s.eip.work/layer":"monitor","k8s.eip.work/name":"kuboard"},"type":"NodePort"}}
  labels:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: kuboard
  name: kuboard
  namespace: kube-system
  resourceVersion: '4716'
spec:
  clusterIP: 10.96.230.238
  ports:
    - name: http
      nodePort: 32567
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: kuboard
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    k8s.eip.work/displayName: kuboard
    k8s.eip.work/workload: kuboard
    nginx.com/sticky-cookie-services: serviceName=kuboard srv_id expires=1h path=/
    nginx.org/websocket-services: kuboard
  labels:
    k8s.eip.work/layer: monitor
    k8s.eip.work/name: kuboard
  name: kuboard
  namespace: kube-system
  resourceVersion: '2779424'
spec:
  rules:
    - host: kuboard.dev.hankutech.com
      http:
        paths:
          - backend:
              serviceName: kuboard
              servicePort: http
            path: /


